import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Pencil } from "lucide-react";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SketchGuess",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<header className="px-4 lg:px-6 h-14 flex items-center bg-[#F8F9FA] border-b-[1px] border-b-gray-300 border-solid rounded-md">          <Link className="flex items-center justify-center" href="/">
            <Pencil className="h-6 w-6 text-primary" />
            <span className="ml-2 text-2xl font-bold text-primary">SketchGuess</span>
          </Link>
        </header>
        {children}
        <Toaster/>
      </body>
    </html>
  );
}
